# Generated by Django 2.2.6 on 2021-06-21 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='asix名')),
                ('cpuMhz', models.CharField(max_length=10, verbose_name='cpu频率(MHZ)')),
                ('cpuUsagePercent', models.CharField(max_length=5, verbose_name='cpu使用率(%)')),
                ('maxMemory', models.CharField(max_length=10, verbose_name='内存最大值(GB)')),
                ('memoryUsage', models.CharField(max_length=10, verbose_name='内存使用(GB)')),
                ('memoryUsagePercent', models.CharField(max_length=5, verbose_name='内存使用率(%)')),
                ('numCpuCores', models.CharField(max_length=3, verbose_name='cpu的核数')),
                ('numCpuPkgs', models.CharField(max_length=3, verbose_name='cpu处理器数量')),
                ('storage_percent', models.CharField(max_length=6, verbose_name='磁盘的使用率')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EsixVm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('vmName', models.CharField(max_length=50, verbose_name='虚拟机名')),
                ('maxVmCpuUsage', models.CharField(max_length=10, verbose_name='cpu最大值(MHZ)')),
                ('numCpu', models.CharField(max_length=3, verbose_name='cpu的核数')),
                ('storage_percent', models.CharField(max_length=6, verbose_name='磁盘使用率(%)')),
                ('vmCpuDemand', models.CharField(max_length=5, verbose_name='cpuDemand')),
                ('vmCpuUsage', models.CharField(max_length=5, verbose_name='cpu使用(MHZ)')),
                ('vmCpuUsagePercent', models.CharField(max_length=6, verbose_name='cpu使用率(%)')),
                ('vmMemoryUsage', models.CharField(max_length=10, verbose_name='内存使用(MHZ)')),
                ('vmMemoryUsagePercent', models.CharField(max_length=6, verbose_name='内存使用率(%)')),
                ('esixName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_application.Esix', verbose_name='asix名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
